;; [[file:init.org::*Eval-and-run: ~C-x C-e~ on test forms][Eval-and-run: ~C-x C-e~ on test forms:1]]
(defvar deftestfixture--registry (make-hash-table :test 'eq)
  "Set of macro names generated by `deftestfixture'.
Used by `my/eval-last-sexp--run-test' to detect when `C-x C-e'
is invoked on a test form, so it can eval-and-run in one step.")

(defun my/eval-last-sexp--run-test (&rest _)
  "After `eval-last-sexp', if the form was a `deftestfixture'-generated
test, run it immediately.  This turns `C-x C-e' into eval-and-run
for test forms — zero extra keystrokes."
  (save-excursion
    (backward-sexp)
    (when-let* ((form (sexp-at-point))
                (_    (consp form))
                (head (car form))
                (_    (gethash head deftestfixture--registry)))
      ;; Macroexpand to find the ert-deftest name.
      (let ((expanded (macroexpand-1 form)))
        (when (and (consp expanded)
                   (eq (car expanded) 'ert-deftest))
          (let ((test-name (cadr expanded)))
            (message "Running test: %s" test-name)
            (ert test-name)))))))

(advice-add 'eval-last-sexp :after #'my/eval-last-sexp--run-test)

(defvar deftest-space "·"
  "The symbol used in place of whitespace in test names.
The default is interpunct style (middle dot).  Alternatives:
  - Hyphens:     OSBE-org-source-exports
  - Snakecase:   OSBE_org_source_exports
  - Underbracket: OSBE␣org␣source␣exports")

(cl-defmacro deftestfixture (name &optional docstring-or-form fixture-form)
  "Define a new test macro NAME that wraps each test body in FIXTURE-FORM.
A test fixture is the fixed baseline state that tests run against —
the setup that must be in place before the test logic executes.  By
way of example: a temp directory, a database connection, or config
variable bindings.  The name reads as \"define a test-with-fixture
macro\", which is precisely what it does.

ERT (§6.2) deliberately omits fixture syntax, noting that
`with-my-fixture' macros are the idiomatic Lisp approach and that
\"special syntax for them could be added but would provide only a
minor simplification.\"  This macro is that minor simplification:
it defines the `with-my-fixture' wrapper and wires it into
`ert-deftest' — with string-based naming and auto-derived tags —
in one step.

Each generated macro is also registered so that `C-x C-e'
(`eval-last-sexp') both defines and runs the test in one
keystroke — no separate `M-x ert' invocation needed.

NAME is the symbol for the generated macro.  DOCSTRING-OR-FORM is
either a documentation string (when FIXTURE-FORM is also provided)
or the fixture form itself (when no docstring is needed).  When
both are omitted, the generated macro has no fixture — its body is
spliced directly into `ert-deftest'.

FIXTURE-FORM is an expression with a hole for the body — represented
by the symbol `&body'.  When nil, the body is spliced directly
\(no wrapping).

The generated macro has the signature:
  (NAME DESCRIPTION &optional TAGS &rest BODY)
where DESCRIPTION is a string and TAGS is an optional vector.

Example — define `deftest' (the identity, no fixture):
  (deftestfixture deftest)

Even this trivial case is already an improvement over raw
`ert-deftest': test names are natural-language strings (not
hand-mangled symbols), tags are auto-derived from the first
word, and the boilerplate docstring + :tags declaration
disappears entirely.

Example — define `defworkitemtest' with a docstring and fixture:
  (deftestfixture defworkitemtest
    \"Bind Gerrit/Jira config vars to safe test defaults.\"
    (let ((my\\\\jira-ticket-regex ...)
          (my\\\\gerrit-base-url ...))
      &body))

Then:
  (defworkitemtest \"work-item shows Jira ticket\" [work-item]
    (should ...))

expands to an `ert-deftest' wrapped in the fixture bindings.

Example — define `deforgtest' for config-smoke tests that need an
org-mode buffer:
  (deftestfixture deforgtest
    \"Temp org-mode buffer with auto-cleanup.\"
    (let ((*original-test-buffer* (generate-new-buffer \"*test-org*\")))
      (switch-to-buffer *original-test-buffer*)
      (org-mode)
      (unwind-protect (progn &body)
        (ignore-errors (org-clock-out))
        (when (get-buffer *original-test-buffer*)
          (kill-buffer *original-test-buffer*)))))

Then:
  (deforgtest \"C-RET creates heading with CREATED\" [config-smoke]
    (execute-kbd-macro (kbd \"C-<return>\"))
    (insert \"My neato notes\")
    (should (org-entry-get (point) \"CREATED\")))

The body can reference `*original-test-buffer*' after switching
away (e.g., to verify C-c SPC jumps back).  The cleanup phase
clocks out any dangling clock, then kills the buffer — no
switch-to-buffer, unwind-protect, or kill-buffer needed in tests."
  (declare (indent 1))
  ;; Disambiguate: if DOCSTRING-OR-FORM is a string, it's a docstring
  ;; and FIXTURE-FORM is the fixture.  Otherwise DOCSTRING-OR-FORM is
  ;; the fixture and there is no docstring.
  (let* ((user-docstring (when (stringp docstring-or-form)
                           docstring-or-form))
         (fixture-form   (if (stringp docstring-or-form)
                             fixture-form
                           docstring-or-form))
         (ert-usage "\n\n\
BODY is evaluated as a `progn' when the test is run.  It should
signal a condition on failure or just return if the test passes.

`should', `should-not', `should-error', `skip-when', and
`skip-unless' are useful for assertions in BODY.

Use `ert' to run tests interactively.  Even easier: `C-x C-e'
at the end of a test form both defines and runs it in one
keystroke, courtesy of `deftestfixture--registry'.

Tests that are expected to fail can be marked as such
using :expected-result.  See `ert-test-result-type-p' for a
description of valid values for RESULT-TYPE.

Macros in BODY are expanded when the test is defined, not when it
is run.  If a macro (possibly with side effects) is to be tested,
it has to be wrapped in `(eval (quote ...))'.")
         (docstring
          (concat
           (or user-docstring
               (format "Test macro generated by `deftestfixture'.%s"
                       (if fixture-form
                           (format "\nFixture: %S" fixture-form)
                         "")))
           ert-usage))
         (assert-msg
          (format "\"%s\" expects its first argument to be a string literal"
                  name))
         (wrap-expr
          (if fixture-form
              `(list
                (cl-subst (cons 'progn actual-body) '&body
                          ',fixture-form))
            'actual-body)))
    `(progn
       (puthash ',name t deftestfixture--registry)
       (cl-defmacro ,name (description &optional tags &rest body)
         ,docstring
         (declare (indent defun))
         (cl-assert (stringp description) nil ,assert-msg)
         (let*
             ((replacements
               `((" " . ,deftest-space)
                 ("`" . "") ("'" . "")
                 ("," . "︐") ("`" . "‵")
                 (";" . "︔") ("[" . "⁅") ("]" . "⁆")))
              (provided-tags (seq--into-list (and (vectorp tags) tags)))
              (test-name
               (concat
                (if provided-tags
                    (format "%s··⇨··"
                            (s-join "︐" (mapcar #'prin1-to-string
                                                provided-tags)))
                  "")
                (thread-last description s-trim s-collapse-whitespace
                             (s-replace-all replacements))))
              (method-being-tested
               (thread-last description s-trim (s-split " ") car
                            (s-replace-all replacements)))
              (actual-body (if (vectorp tags) body (cons tags body)))
              (wrapped-body ,wrap-expr))
           `(ert-deftest ,(intern test-name) ()
              :tags ',(cons method-being-tested provided-tags)
              ,@wrapped-body))))))

(deftestfixture deftest)

;;  Switches to a temp org-mode buffer, runs the body, kills the buffer even on failure.
(deftestfixture deforgtest
  "Switch to a temporary org-mode buffer, run BODY, then kill the buffer.
Most config-smoke tests need an org buffer with mode hooks fired —
this fixture axes that boilerplate.  The buffer object is bound to
`*original-test-buffer*' so tests can reference it after switching away."
  (let ((*original-test-buffer* (generate-new-buffer "*test-org*")))
    (switch-to-buffer *original-test-buffer*)
    (org-mode)
    (unwind-protect
        (progn &body)
      ;; Even if some assertion fails, we should clock-out! No dangling clocks!
      (ignore-errors (org-clock-out))
      ;; Kill the buffer even when a `should' signals failure —
      ;; without unwind-protect, a failing assertion would leak it.
      (when (get-buffer *original-test-buffer*)
        (kill-buffer *original-test-buffer*)))))
;; Eval-and-run: ~C-x C-e~ on test forms:1 ends here

;; [[file:init.org::*Eval-and-run: ~C-x C-e~ on test forms][Eval-and-run: ~C-x C-e~ on test forms:2]]
;; The 😴 macro defers code via `run-with-idle-timer'.  In batch mode
;; those timers never fire, so hooks, mode setups, etc. are absent.
;; Force every pending timer to fire now, making the deferred init eager.
(mapc (lambda (timer) (ignore-errors (timer-event-handler timer))) timer-idle-list)

;; Several use-package declarations register global modes via
;; :hook (after-init . global-*-mode).  In CI, after-init-hook fires
;; before load-file "init.el", so these registrations miss the boat.
;; Re-run the hook so they activate.
(run-hooks 'after-init-hook)

(advice-add 'org-resolve-clocks :override #'ignore)
;; Eval-and-run: ~C-x C-e~ on test forms:2 ends here

(ert-deftest company-works-as-expected-in-text-mode ()
  :tags '(company)
  (skip-unless nil) ;; Company-mode not in use; revisit when re-enabled.
  (switch-to-buffer "*TESTING COMPANY MODE ~ Text*")

  ;; Ensure we have a clear buffer, and enter some text. (Namely, Python code).
  (erase-buffer)
  (insert "\n def first(x): pass")
  (insert "\n def fierce(a, b): pass")

  ;; Completion anything mode is enabled by default.
  (should company-mode)

  ;; There are 2 completion candidates: The two we wrote.
  (insert "\n fi")
  (company-manual-begin) ;; i.e., C-/
  (should (equal company-candidates '("fierce" "first")))

  ;; [fi ↦ fierce] Default option is the most recently matching written word.
  (insert "\n fi")
  (execute-kbd-macro (kbd "C-/ <return>"))
  (should (looking-back "fierce"))

  ;; [fi ↦ first] We can use M-2 to select the candidate “first”
  (insert "\n fi")
  (execute-kbd-macro (kbd "C-/ M-2"))
  (should (looking-back "first"))

  (kill-buffer))

;; Let's enter Python mode and see how things change

(ert-deftest company-shows-keywords-alongside-completions-alphabetically ()
  :tags '(company)
  (skip-unless nil) ;; Company-mode not in use; revisit when re-enabled.
  (switch-to-buffer "*TESTING COMPANY MODE ~ Python*")
  (python-mode)

  ;; Ensure we have a clear buffer, and enter some text. (Namely, Python code).
  (erase-buffer)
  (insert "\n def first(x): pass")
  (insert "\n def fierce(a, b): pass")

  ;; There are 3 completion candidates: The two we wrote, & the third being a Python keyword.
  (insert "\n fi")
  (company-manual-begin)
  (should (equal company-candidates '("fierce" "first" #("finally" 0 7 (company-backend company-keywords)))))

  ;; Candidates are shown alphabetically: M-2 yields “finally”.
  (execute-kbd-macro (kbd "C-g C-/ M-2")) ;; Quit and restart the completion, to get to starting position, then M-2.
  (should (looking-back "finally"))

  (kill-buffer))

;; [[file:init.org::#Coding-with-a-Fruit-Salad-Semantic-Highlighting][Coding with a Fruit Salad: Semantic Highlighting:2]]
(deftest "prog-mode activates indentation and completion" [config-smoke]
  (skip-unless (fboundp 'aggressive-indent-mode))
  (switch-to-buffer "*test-prog-mode*")
  (unwind-protect
      (progn
        (emacs-lisp-mode)
        (should aggressive-indent-mode)
        ;; corfu's globalized mode skips noninteractive sessions (no
        ;; child frames in batch), so verify the global config instead.
        (should (bound-and-true-p global-corfu-mode))
        (should eldoc-mode)
        (should color-identifiers-mode))
    (kill-buffer "*test-prog-mode*")))
;; Coding with a Fruit Salad: Semantic Highlighting:2 ends here

;; [[file:init.org::*E2E Test][E2E Test:1]]
(require 'lf) ;; For `lf-unindent'; installed via use-package but deferred.

(defun my/test--name-to-username (full-name)
  "Derive a Gerrit-style username from FULL-NAME.
Lowercases the first initial and surname: \"Grace Hopper\" → \"ghopper\"."
  (let ((parts (s-split " " (s-trim full-name))))
    (downcase (concat (substring (car parts) 0 1)
                      (car (last parts))))))

(defun my/as-gerrit-patch (spec)
  "Parse a human-readable SPEC string into a Gerrit change alist.
SPEC is a terse commit-message-like block.  Leading indentation is
stripped via `lf-unindent', so callers can indent the string to
match surrounding code:

  (my/as-gerrit-patch \"
      [core] Fix the frobnicate

      BUG-42 #progress

      Owner: Grace Hopper
      Reviewer: Alan Turing
      Added-Reviewer: Ada Lovelace
      Reviewer-Negative: Skynet\")

The first non-blank line becomes `subject'.  Everything before the
metadata lines (Change-Id, Owner, Reviewer, Added-Reviewer,
Reviewer-Negative) forms `commitMessage'.  `Change-Id' is optional —
when present it sets `number' (parsed via `string-to-number'); when
absent, `my/as-gerrit-stack' auto-assigns from the position index.
`Owner' populates the `owner' alist.

Reviewer keywords:
  Reviewer:          voted Code-Review (positive) — appears in both
                     `allReviewers' and `currentPatchSet.approvals'.
  Added-Reviewer:    added but hasn't voted — appears in
                     `allReviewers' only (no approval entry).
  Reviewer-Negative: voted Code-Review -1 — appears in both
                     `allReviewers' and `approvals' with value \"-1\".
  Patchset:          integer, sets `currentPatchSet.number'.
                     Omit for default (no number in the alist).
  Comments:          integer, generates that many stub `comments' entries.
                     Omit for default (empty comments list).
  Last-Updated:      relative age like \"5 days ago\" or \"3 months ago\".
                     Converted to a `lastUpdated' epoch for staleness."
  (let* ((lines (s-lines (s-trim (lf-unindent spec))))
         (subject (car lines))
         ;; Partition into commit-message vs. metadata lines.
         (meta-re (concat "^\\(Change-Id\\|Owner\\|Reviewer"
                          "\\|Added-Reviewer\\|Reviewer-Negative"
                          "\\|Last-Updated\\|Patchset\\|Comments\\):"))
         (msg-lines (-take-while
                     (lambda (l) (not (s-matches-p meta-re l)))
                     lines))
         (meta-lines (-drop (length msg-lines) lines))
         (commit-msg (s-trim (s-join "\n" msg-lines)))
         ;; Parse metadata.
         (number nil) (owner-name nil) (last-updated nil)
         (patchset-num nil) (comment-count nil)
         (reviewers nil) (added-reviewers nil) (neg-reviewers nil))
    (dolist (l meta-lines)
      (cond
       ((s-prefix-p "Change-Id:" l)
        (setq number (string-to-number (s-trim (substring l 10)))))
       ((s-prefix-p "Owner:" l)
        (setq owner-name (s-trim (substring l 6))))
       ((s-prefix-p "Last-Updated:" l)
        (let ((val (s-trim (substring l 13))))
          (setq last-updated
                (if (string-match "\\([0-9]+\\) \\(day\\|week\\|month\\|year\\)s? ago" val)
                    (let* ((n (string-to-number (match-string 1 val)))
                           (unit (match-string 2 val))
                           (secs (* n (pcase unit
                                        ("day" 86400)
                                        ("week" 604800)
                                        ("month" 2592000)
                                        ("year" 31536000)))))
                      (truncate (- (float-time) secs)))
                  (string-to-number val)))))
       ((s-prefix-p "Reviewer-Negative:" l)
        (push (s-trim (substring l 18)) neg-reviewers))
       ((s-prefix-p "Added-Reviewer:" l)
        (push (s-trim (substring l 15)) added-reviewers))
       ((s-prefix-p "Reviewer:" l)
        (push (s-trim (substring l 9)) reviewers))
       ((s-prefix-p "Patchset:" l)
        (setq patchset-num (string-to-number (s-trim (substring l 9)))))
       ((s-prefix-p "Comments:" l)
        (setq comment-count (string-to-number (s-trim (substring l 9)))))))
    (setq reviewers (nreverse reviewers)
          added-reviewers (nreverse added-reviewers)
          neg-reviewers (nreverse neg-reviewers))
    (let ((all-rv (-map (lambda (r)
                          `((name . ,r)
                            (username . ,(my/test--name-to-username r))))
                        (append reviewers added-reviewers neg-reviewers)))
          (pos-approvals
           (-map (lambda (r)
                   `((type . "Code-Review")
                     (by (name . ,r)
                         (username . ,(my/test--name-to-username r)))))
                 reviewers))
          (neg-approvals
           (-map (lambda (r)
                   `((type . "Code-Review") (value . "-1")
                     (by (name . ,r)
                         (username . ,(my/test--name-to-username r)))))
                 neg-reviewers)))
      `((number . ,number)
        (subject . ,subject)
        (commitMessage . ,commit-msg)
        ,@(when last-updated `((lastUpdated . ,last-updated)))
        (owner (name . ,owner-name)
               (username . ,(my/test--name-to-username owner-name)))
        ,@(when all-rv `((allReviewers . ,all-rv)))
        (currentPatchSet
         ,@(when patchset-num `((number . ,patchset-num)))
         (approvals . ,(append pos-approvals neg-approvals)))
        ,@(when comment-count
            `((comments . ,(-map (lambda (i)
                                   `((timestamp . ,(truncate (float-time)))
                                     (message . ,(format "stub comment %d" i))))
                                 (number-sequence 1 comment-count)))))))))

(defun my/as-gerrit-stack (&rest specs)
  "Map `my/as-gerrit-patch' over SPECS, returning a list of change alists.
Each element of SPECS is a human-readable patch string (see
`my/as-gerrit-patch' for the format).  A single-element list is
a valid stack — useful for the lone-change happy path.

The change `number' is auto-assigned from the position index
(0, 1, 2, ...) when the spec omits a `Change-Id:' line —
removing boilerplate from tests."
  (--map-indexed (let ((c (my/as-gerrit-patch it)))
                   (unless (alist-get 'number c)
                     (setf (alist-get 'number c) it-index))
                   c)
                 specs))

(deftestfixture defworkitemtest
  "Bind Gerrit/Jira config vars that work-item functions read,
so tests run without private.el."
  (let ((my\jira-ticket-regex "\\(BUG-[0-9]+\\)")
        (my\gerrit-base-url "https://gerrit.example.com")
        (my\gerrit-project-path "/c/repo/+/"))
    &body))

(defworkitemtest "work-item-to-string shows the tip's Jira ticket when the stack intersection is empty" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[core] Refactor helper

                  Owner: Grace Hopper"

                 "[core] Add frobnicate validation

                  BUG-42 #progress

                  Owner: Grace Hopper"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-42" rendered))
    (should (s-contains-p "Grace Hopper" rendered))))

(defworkitemtest "work-item-to-string shows the shared Jira ticket when every change references it" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[lang] Step one

                  BUG-7 #progress

                  Owner: Ada Lovelace"

                 "[lang] Step two

                  BUG-7 #progress

                  Owner: Ada Lovelace"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-7" rendered))
    (should (s-contains-p "Ada Lovelace" rendered))))

(defworkitemtest "work-item-to-string shows Jira ticket for a single-change stack" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[ui] Fix button alignment

                  BUG-101 #progress

                  Owner: Alan Turing"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-101" rendered))
    (should (s-contains-p "Alan Turing" rendered))))

(defworkitemtest "reviews-needed splits multi-author stack into per-author items" [work-item]
  (let* ((my\gerrit-user "mhopper")
         (stack (my/as-gerrit-stack
                 "[core] Base refactor

                  BUG-52 #progress

                  Owner: Ada Lovelace"

                 "[core] Extend refactor

                  BUG-52 #progress

                  Owner: Ada Lovelace"

                 "[core] Add validation

                  BUG-61 #progress

                  Owner: Grace Hopper"

                 "[core] Wire up UI

                  BUG-61 #progress

                  Owner: Grace Hopper"))
         (items (work-items-from-review-stack stack my\gerrit-user)))
    ;; Two distinct non-self authors → two work-items.
    (should (= 2 (length items)))
    (let ((authors (-map #'work-item-author items)))
      (should (member "Ada Lovelace" authors))
      (should (member "Grace Hopper" authors)))
    ;; Ada's item links to her tip (change 1) with her ticket.
    (let ((ada (--first (equal "Ada Lovelace" (work-item-author it)) items)))
      (should (s-contains-p "/1" (work-item-tip-url ada)))
      (should (equal "BUG-52" (work-item-jira ada))))
    ;; Grace's item links to her tip (change 3) with her ticket.
    (let ((grace (--first (equal "Grace Hopper" (work-item-author it)) items)))
      (should (s-contains-p "/3" (work-item-tip-url grace)))
      (should (equal "BUG-61" (work-item-jira grace))))))

(defworkitemtest "reviews-needed splits same-author multi-ticket stack into per-ticket items" [work-item]
  (let* ((my\gerrit-user "mhopper")
         (stack (my/as-gerrit-stack
                 "[lang] Add pattern filtering

                  BUG-48 #resolve

                  Owner: Alan Turing"

                 "[lang] Add family-based schema

                  BUG-51 #progress

                  Owner: Alan Turing"))
         (items (work-items-from-review-stack stack my\gerrit-user)))
    ;; Same author, different tickets → two work-items.
    (should (= 2 (length items)))
    (let ((tickets (-map #'work-item-jira items)))
      (should (member "BUG-48" tickets))
      (should (member "BUG-51" tickets)))
    ;; Each item links to the correct change.
    (let ((bug48 (--first (equal "BUG-48" (work-item-jira it)) items)))
      (should (s-contains-p "/0" (work-item-tip-url bug48))))
    (let ((bug51 (--first (equal "BUG-51" (work-item-jira it)) items)))
      (should (s-contains-p "/1" (work-item-tip-url bug51))))))

(defworkitemtest "reviews-needed produces one item for single-author single-ticket stack" [work-item]
  (let* ((my\gerrit-user "mhopper")
         (stack (my/as-gerrit-stack
                 "[ui] Fix spacing

                  BUG-99 #progress

                  Owner: Alan Turing"))
         (items (work-items-from-review-stack stack my\gerrit-user)))
    (should (= 1 (length items)))
    (should (equal "Alan Turing" (work-item-author (car items))))
    (should (equal "BUG-99" (work-item-jira (car items))))))

(defworkitemtest "extract-jira-tickets uses last reference as primary ticket" [work-item]
  (let* ((change (my/as-gerrit-patch
                  "[irule] Support matches_regex operator

                   BUG-30 #progress
                   BUG-49 #progress

                   Owner: Grace Hopper"))
         (tickets (my/gerrit--extract-jira-tickets change)))
    ;; Only the last Jira reference is returned — it is the primary ticket.
    (should (equal '("BUG-49") tickets))))

(defworkitemtest "reviews-needed drops jira-less changes from multi-ticket stack" [work-item]
  (let* ((my\gerrit-user "ghopper")
         (stack (my/as-gerrit-stack
                 "[predict, refactor] Convert widget tests

                  BUG-77 #progress

                  Owner: Alan Turing"

                 "[predict, refactor] Convert gadget tests

                  Owner: Alan Turing"

                 "[predict] Reject delete of nonexistent item

                  BUG-88 #resolve

                  Owner: Alan Turing"))
         (items (work-items-from-review-stack stack my\gerrit-user)))
    ;; Two distinct Jira tickets → two work-items.
    ;; The middle change (no Jira) is silently absorbed, not a third item.
    (should (= 2 (length items)))
    (let ((tickets (-map #'work-item-jira items)))
      (should (member "BUG-77" tickets))
      (should (member "BUG-88" tickets))
      (should-not (member nil tickets)))))

(defworkitemtest "reviews-needed still shows item when no change has a jira ticket" [work-item]
  (let* ((my\gerrit-user "ghopper")
         (stack (my/as-gerrit-stack
                 "[predict] Add widget filtering

                  Owner: Alan Turing"

                 "[predict] Reject bogus widget delete

                  Owner: Alan Turing"))
         (items (work-items-from-review-stack stack my\gerrit-user)))
    ;; No Jira tickets anywhere, but the review item must still appear.
    (should (= 1 (length items)))
    (should (equal "Alan Turing" (work-item-author (car items))))))

(defworkitemtest "please-review shows non-voting reviewer by name" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[core, refactor] Rename FrobExpr.All to Inside

                  BUG-123 #progress

                  Owner: Grace Hopper
                  Added-Reviewer: Alan Turing"

                 "[core] Restrict FrobValue to current use-case

                  BUG-123 #related

                  Owner: Grace Hopper"))
         (item (work-item-from-stack stack 'please-review))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "Alan Turing" rendered))
    (should (not (s-contains-p "Reviewers" rendered)))))

(defworkitemtest "please-review surfaces bot with negative Code-Review" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[core] Fix the frobnicate

                  BUG-42 #progress

                  Owner: Grace Hopper
                  Added-Reviewer: Alan Turing
                  Reviewer-Negative: Skynet"))
         (item (work-item-from-stack stack 'please-review))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "Alan Turing" rendered))
    (should (s-contains-p "Skynet" rendered))))

(defworkitemtest "please-review filters out bot with positive Code-Review" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[core] Fix the frobnicate

                  BUG-42 #progress

                  Owner: Grace Hopper
                  Added-Reviewer: Alan Turing
                  Reviewer: Skynet"))
         (item (work-item-from-stack stack 'please-review))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "Alan Turing" rendered))
    (should (not (s-contains-p "Skynet" rendered)))))

(defworkitemtest "multi-ticket stack produces one work-item per ticket" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[irule] Support matches_regex operator

                  BUG-49 #resolve

                  Owner: Grace Hopper"

                 "[irule] Suppress substitution in braced strings

                  BUG-48 #resolve

                  Owner: Grace Hopper"))
         (items (work-items-from-stack stack 'please-review)))
    ;; Two distinct tickets → two work-items.
    (should (= 2 (length items)))
    (let ((tickets (-map #'work-item-jira items)))
      (should (member "BUG-49" tickets))
      (should (member "BUG-48" tickets)))))

(defworkitemtest "jira-less item renders with Sidequest prefix" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[lang] Introduce QuadraticSorter

                  !NO_JIRA

                  Owner: Ada Lovelace
                  Added-Reviewer: Grace Hopper"))
         (item (work-item-from-stack stack 'my-needing-action))
         (str (work-item-to-string item)))
    ;; No Jira → title appears as Sidequest{ ... } prefix.
    (should (string-match-p "Sidequest{ Introduce QuadraticSorter }" str))
    ;; Should NOT contain a Jira link.
    (should-not (string-match-p "BUG-\\" str))))

(defworkitemtest "age prefix appears in rendered work-item" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[base] Simplify helper utility

                  BUG-77 #progress

                  Owner: Grace Hopper
                  Added-Reviewer: Alan Turing
                  Last-Updated: 5 months ago"))
         (item (work-item-from-stack stack 'please-review))
         (str (work-item-to-string item)))
    ;; Age prefix appears.
    (should (string-match-p "\\[5 months\\]" str))
    ;; Jira is still there too.
    (should (string-match-p "BUG-77" str))))

(defworkitemtest "age is nil when no lastUpdated on change" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[base] Quick fix

                  BUG-88 #progress

                  Owner: Ada Lovelace"))
         (item (work-item-from-stack stack 'wip)))
    ;; No Last-Updated in spec → age slot is nil.
    (should-not (work-item-age item))
    ;; Rendered string has no age prefix (e.g. "[5 days]").
    (should-not (string-match-p "\\[[0-9]+ \\(day\\|week\\|month\\|year\\)" (work-item-to-string item)))))

(defworkitemtest "sort: urgent first, stalest-first everywhere, sidequests last" [work-item]
  (let* ((stack-old (my/as-gerrit-stack
                     "[base] Old refactor

                      BUG-10 #progress

                      Owner: Grace Hopper
                      Last-Updated: 6 months ago"))
         (stack-new (my/as-gerrit-stack
                     "[base] Recent tweak

                      BUG-20 #progress

                      Owner: Alan Turing
                      Last-Updated: 2 days ago"))
         (stack-urgent (my/as-gerrit-stack
                        "[base] Urgent fix

                         BUG-30 #progress

                         Owner: Ada Lovelace
                         Last-Updated: 1 days ago"))
         (stack-side-old (my/as-gerrit-stack
                          "[base] Ancient cleanup

                           !NO_JIRA

                           Owner: Grace Hopper
                           Last-Updated: 1 years ago"))
         (stack-side-new (my/as-gerrit-stack
                          "[base] Tidy up helpers

                           !NO_JIRA

                           Owner: Alan Turing
                           Last-Updated: 3 days ago"))
         (old-item (work-item-from-stack stack-old 'please-review))
         (new-item (work-item-from-stack stack-new 'please-review))
         (urgent-item (work-item-from-stack stack-urgent 'please-review))
         (side-old (work-item-from-stack stack-side-old 'please-review))
         (side-new (work-item-from-stack stack-side-new 'please-review)))
    (setf (work-item-urgent urgent-item) t)
    (let ((sorted (work-item--sort
                   (list new-item side-new old-item urgent-item side-old))))
      ;; Urgent first.
      (should (eq (nth 0 sorted) urgent-item))
      ;; Stalest normal item before newer.
      (should (eq (nth 1 sorted) old-item))
      (should (eq (nth 2 sorted) new-item))
      ;; Sidequests last, also stalest-first.
      (should (eq (nth 3 sorted) side-old))
      (should (eq (nth 4 sorted) side-new)))))
;; E2E Test:1 ends here

;; [[file:init.org::*Also, logging][Also, logging:2]]
(deftest "org workflow states are configured" [config-smoke]
  (should (equal org-todo-keywords
                 '((sequence "TODO(t)" "INVESTIGATED(i)" "STARTED(s)"
                             "|" "PAUSED(p@/!)" "WAITING(w)" "APPROVED(a)"
                             "REFERENCE(r)" "DONE(d)" "CANCELLED(c@)"))))
  (should (equal org-log-done 'time)))

(deforgtest "org speed keys transition TODO state" [config-smoke]
  (should org-use-speed-commands)
  (insert "* TODO Test task\n")
  (goto-char (point-min))
  (execute-kbd-macro (kbd "t i"))
  (should (equal (org-entry-get (point) "TODO") "INVESTIGATED")))

(deforgtest "DONE state adds CLOSED timestamp" [config-smoke]
  (insert "* TODO Wrap it up\n")
  (goto-char (point-min))
  (org-todo "DONE")
  (should (org-entry-get (point) "CLOSED")))
;; Also, logging:2 ends here

;; [[file:init.org::*Adding New *Tasks/Notes* Quickly Without Disturbing The Current Task Content][Adding New *Tasks/Notes* Quickly Without Disturbing The Current Task Content:2]]
(deforgtest "C-RET creates org heading with CREATED property" [config-smoke]
  (execute-kbd-macro (kbd "C-<return>"))
  (insert "My neato notes")
  (should (s-matches? (format-time-string "\\[%Y-%m-%d")
                      (or (org-entry-get (point) "CREATED") ""))))

(deforgtest "org heading gets SCHEDULED and DEADLINE" [config-smoke]
  (execute-kbd-macro (kbd "C-<return>"))
  (insert "Planned task")
  (execute-kbd-macro (kbd "C-c C-s <return>"))
  (execute-kbd-macro (kbd "C-c C-d <return>"))
  (should (org-entry-get (point) "SCHEDULED"))
  (should (org-entry-get (point) "DEADLINE")))
;; Adding New *Tasks/Notes* Quickly Without Disturbing The Current Task Content:2 ends here

;; [[file:init.org::#drag-and-drop-images-into-org-mode][“Smart Paste”: Drag and Drop Images/(Any File!) into Org-Mode:2]]
(deforgtest "smart paste inserts plain text as-is" [config-smoke smart-paste]
  (kill-new "Plain text is pasted as is")
  (my/dwim-paste)
  (should (equal (s-trim (buffer-string))
                 "Plain text is pasted as is")))

(deforgtest "smart paste transforms Gerrit link to Org link" [config-smoke smart-paste]
  ;; Simulate what yank-media does: call the STRING handler directly
  ;; with the clipboard text.  In a GUI, s-v -> my/dwim-paste ->
  ;; yank-media -> STRING handler.  We bypass the clipboard read.
  (my/yank-plaintext-media
   "STRING"
   "12345: [foo, bar] OCaml Syntax: Fix foo bar baz | https://gerrit.example.com/c/abc/+/12345")
  (should (equal (s-trim (buffer-string))
                 "[[https://gerrit.example.com/c/abc/+/12345][OCaml Syntax: Fix foo bar baz]]")))

(deforgtest "C-u prefix does raw paste even for URLs" [config-smoke smart-paste]
  (kill-new "https://github.com/alphapapa/org-ql/tree/master")
  (let ((current-prefix-arg '(4)))
    (my/dwim-paste))
  (should (equal (s-trim (buffer-string))
                 "https://github.com/alphapapa/org-ql/tree/master")))

(deforgtest "smart paste converts URL to titled Org link" [config-smoke smart-paste]
  ;; Fetches the page title over the network --- skip in batch.
  (skip-unless (not noninteractive))
  (my/yank-plaintext-media
   "STRING" "https://github.com/alphapapa/org-ql/tree/master")
  (should (s-starts-with?
           "[[https://github.com/alphapapa/org-ql/tree/master]["
           (s-trim (buffer-string)))))
;; “Smart Paste”: Drag and Drop Images/(Any File!) into Org-Mode:2 ends here

(deforgtest "C-c SPC jumps to clocked task" [config-smoke]
  (require 'org-capture) ;; my/say-bismillah-on-clock-in checks org-capture-mode
  (insert "* TODO Clocked task\n")
  (goto-char (point-min))
  (org-clock-in)
  (switch-to-buffer "*scratch*")
  (should (equal (buffer-name) "*scratch*"))
  (execute-kbd-macro (kbd "C-c SPC"))
  (should (equal (current-buffer) *original-test-buffer*))
  (should (equal (org-get-heading) "TODO Clocked task")))

(deforgtest "org-mode activates completion and eldoc" [config-smoke]
  (skip-unless (fboundp 'eldoc-box-hover-mode))
  (should (bound-and-true-p global-corfu-mode))
  (should eldoc-mode)
  (should eldoc-box-hover-mode))

;; [[file:init.org::*Implementation][Implementation:2]]
(ert-deftest hierarchical-archive-merges-duplicate-headings ()
  "Archiving a child, then its parent, produces a single merged heading."
  :tags '(archive)
  ;; `org-archive-finalize-hook' was introduced in Org 9.8; the hook
  ;; that drives hierarchical archiving simply doesn't fire on older Org.
  (skip-unless (version<= "9.8" org-version))
  (let* ((src-file (make-temp-file "archive-src" nil ".org"
                                   "* A\nSome useful context\n** B\nMore Info\n** C\nBye!\n"))
         (archive-file (concat (file-name-sans-extension src-file) "_archive.org"))
         (org-archive-location (concat archive-file "::"))
         ;; Suppress prompts and messages during the test.
         (inhibit-message t))
    (unwind-protect
        (progn
          ;; Archive ** B
          (find-file src-file)
          (goto-char (point-min))
          (search-forward "** B")
          (my/org-archive-subtree-hierarchically)

          ;; Archive * A (which still carries ** C)
          (goto-char (point-min))
          (search-forward "* A")
          (my/org-archive-subtree-hierarchically)

          ;; Verify: the archive should contain a single * A with
          ;; body text, ** B, and ** C --- no duplicates.
          (with-current-buffer (find-file-noselect archive-file)
            (let ((contents (buffer-string)))
              ;; Exactly one "* A" heading.
              (should (= 1 (s-count-matches "^\\* A$" contents)))
              ;; Body text from the parent is present.
              (should (s-contains-p "Some useful context" contents))
              ;; Both children are present.
              (should (s-contains-p "** B" contents))
              (should (s-contains-p "More Info" contents))
              (should (s-contains-p "** C" contents))
              (should (s-contains-p "Bye!" contents)))))

      ;; Cleanup: silence kill-buffer prompts for modified buffers.
      (--each (list src-file archive-file)
        (-when-let (buf (get-file-buffer it))
          (with-current-buffer buf (set-buffer-modified-p nil))
          (kill-buffer buf))
        (when (file-exists-p it) (delete-file it))))))
;; Implementation:2 ends here

(ert-deftest lsp-hover-shows-type-signature ()
  (skip-unless (fboundp 'lsp-workspace-folders-add))
  ;; Make a temporary scratch.js file with the given contents.
  (-let [scratch.js (make-temp-file "scratch" nil ".js" "const first = (x, y) => 3")]
    (find-file scratch.js)
    (lsp-workspace-folders-add (f-parent scratch.js))
    (lsp)

    ;; lsp-hover uses lsp--eldoc-message, so let's save the hover info.
    (advice-add #'lsp--eldoc-message :before (lambda (&rest msg) (setq my/lsp-hover-message (substring-no-properties (car msg)))))

    (end-of-buffer)
    (insert "\n first")
    (lsp-hover)  ;; Alternatively: (lsp-describe-thing-at-point)
    (should (equal "const first: (x: any, y: any) => number" my/lsp-hover-message))

    (save-buffer)
    (kill-buffer)))
