;; [[file:init.org::*Eval-and-run: ~C-x C-e~ on test forms][Eval-and-run: ~C-x C-e~ on test forms:1]]
(defvar deftestfixture--registry (make-hash-table :test 'eq)
  "Set of macro names generated by `deftestfixture'.
Used by `my/eval-last-sexp--run-test' to detect when `C-x C-e'
is invoked on a test form, so it can eval-and-run in one step.")

(defun my/eval-last-sexp--run-test (&rest _)
  "After `eval-last-sexp', if the form was a `deftestfixture'-generated
test, run it immediately.  This turns `C-x C-e' into eval-and-run
for test forms — zero extra keystrokes."
  (save-excursion
    (backward-sexp)
    (when-let* ((form (sexp-at-point))
                (_    (consp form))
                (head (car form))
                (_    (gethash head deftestfixture--registry)))
      ;; Macroexpand to find the ert-deftest name.
      (let ((expanded (macroexpand-1 form)))
        (when (and (consp expanded)
                   (eq (car expanded) 'ert-deftest))
          (let ((test-name (cadr expanded)))
            (message "Running test: %s" test-name)
            (ert test-name)))))))

(advice-add 'eval-last-sexp :after #'my/eval-last-sexp--run-test)

(defvar deftest-space "·"
  "The symbol used in place of whitespace in test names.
The default is interpunct style (middle dot).  Alternatives:
  - Hyphens:     OSBE-org-source-exports
  - Snakecase:   OSBE_org_source_exports
  - Underbracket: OSBE␣org␣source␣exports")

(cl-defmacro deftestfixture (name &optional docstring-or-form fixture-form)
  "Define a new test macro NAME that wraps each test body in FIXTURE-FORM.
A test fixture is the fixed baseline state that tests run against —
the setup that must be in place before the test logic executes.  By
way of example: a temp directory, a database connection, or config
variable bindings.  The name reads as \"define a test-with-fixture
macro\", which is precisely what it does.

ERT (§6.2) deliberately omits fixture syntax, noting that
`with-my-fixture' macros are the idiomatic Lisp approach and that
\"special syntax for them could be added but would provide only a
minor simplification.\"  This macro is that minor simplification:
it defines the `with-my-fixture' wrapper and wires it into
`ert-deftest' — with string-based naming and auto-derived tags —
in one step.

Each generated macro is also registered so that `C-x C-e'
(`eval-last-sexp') both defines and runs the test in one
keystroke — no separate `M-x ert' invocation needed.

NAME is the symbol for the generated macro.  DOCSTRING-OR-FORM is
either a documentation string (when FIXTURE-FORM is also provided)
or the fixture form itself (when no docstring is needed).  When
both are omitted, the generated macro has no fixture — its body is
spliced directly into `ert-deftest'.

FIXTURE-FORM is an expression with a hole for the body — represented
by the symbol `&body'.  When nil, the body is spliced directly
\(no wrapping).

The generated macro has the signature:
  (NAME DESCRIPTION &optional TAGS &rest BODY)
where DESCRIPTION is a string and TAGS is an optional vector.

Example — define `deftest' (the identity, no fixture):
  (deftestfixture deftest)

Even this trivial case is already an improvement over raw
`ert-deftest': test names are natural-language strings (not
hand-mangled symbols), tags are auto-derived from the first
word, and the boilerplate docstring + :tags declaration
disappears entirely.

Example — define `defworkitemtest' with a docstring and fixture:
  (deftestfixture defworkitemtest
    \"Bind Gerrit/Jira config vars to safe test defaults.\"
    (let ((my\\\\jira-ticket-regex ...)
          (my\\\\gerrit-base-url ...))
      &body))

Then:
  (defworkitemtest \"work-item shows Jira ticket\" [work-item]
    (should ...))

expands to an `ert-deftest' wrapped in the fixture bindings."
  (declare (indent 1))
  ;; Disambiguate: if DOCSTRING-OR-FORM is a string, it's a docstring
  ;; and FIXTURE-FORM is the fixture.  Otherwise DOCSTRING-OR-FORM is
  ;; the fixture and there is no docstring.
  (let* ((user-docstring (when (stringp docstring-or-form)
                           docstring-or-form))
         (fixture-form   (if (stringp docstring-or-form)
                             fixture-form
                           docstring-or-form))
         (ert-usage "\n\n\
BODY is evaluated as a `progn' when the test is run.  It should
signal a condition on failure or just return if the test passes.

`should', `should-not', `should-error', `skip-when', and
`skip-unless' are useful for assertions in BODY.

Use `ert' to run tests interactively.  Even easier: `C-x C-e'
at the end of a test form both defines and runs it in one
keystroke, courtesy of `deftestfixture--registry'.

Tests that are expected to fail can be marked as such
using :expected-result.  See `ert-test-result-type-p' for a
description of valid values for RESULT-TYPE.

Macros in BODY are expanded when the test is defined, not when it
is run.  If a macro (possibly with side effects) is to be tested,
it has to be wrapped in `(eval (quote ...))'.")
         (docstring
          (concat
           (or user-docstring
               (format "Test macro generated by `deftestfixture'.%s"
                       (if fixture-form
                           (format "\nFixture: %S" fixture-form)
                         "")))
           ert-usage))
         (assert-msg
          (format "\"%s\" expects its first argument to be a string literal"
                  name))
         (wrap-expr
          (if fixture-form
              `(list
                (cl-subst (cons 'progn actual-body) '&body
                          ',fixture-form))
            'actual-body)))
    `(progn
       (puthash ',name t deftestfixture--registry)
       (cl-defmacro ,name (description &optional tags &rest body)
         ,docstring
         (declare (indent defun))
         (cl-assert (stringp description) nil ,assert-msg)
         (let*
             ((replacements
               `((" " . ,deftest-space)
                 ("`" . "") ("'" . "")
                 ("," . "︐") ("`" . "‵")
                 (";" . "︔") ("[" . "⁅") ("]" . "⁆")))
              (provided-tags (seq--into-list (and (vectorp tags) tags)))
              (test-name
               (concat
                (if provided-tags
                    (format "%s··⇨··"
                            (s-join "︐" (mapcar #'prin1-to-string
                                                provided-tags)))
                  "")
                (thread-last description s-trim s-collapse-whitespace
                             (s-replace-all replacements))))
              (method-being-tested
               (thread-last description s-trim (s-split " ") car
                            (s-replace-all replacements)))
              (actual-body (if (vectorp tags) body (cons tags body)))
              (wrapped-body ,wrap-expr))
           `(ert-deftest ,(intern test-name) ()
              :tags ',(cons method-being-tested provided-tags)
              ,@wrapped-body))))))

(deftestfixture deftest)
;; Eval-and-run: ~C-x C-e~ on test forms:1 ends here

(ert-deftest company-works-as-expected-in-text-mode ()
  :tags '(company)
  (skip-unless (fboundp 'company-manual-begin))
  (switch-to-buffer "*TESTING COMPANY MODE ~ Text*")

  ;; Ensure we have a clear buffer, and enter some text. (Namely, Python code).
  (erase-buffer)
  (insert "\n def first(x): pass")
  (insert "\n def fierce(a, b): pass")

  ;; Completion anything mode is enabled by default.
  (should company-mode)

  ;; There are 2 completion candidates: The two we wrote.
  (insert "\n fi")
  (company-manual-begin) ;; i.e., C-/
  (should (equal company-candidates '("fierce" "first")))

  ;; [fi ↦ fierce] Default option is the most recently matching written word.
  (insert "\n fi")
  (execute-kbd-macro (kbd "C-/ <return>"))
  (should (looking-back "fierce"))

  ;; [fi ↦ first] We can use M-2 to select the candidate “first”
  (insert "\n fi")
  (execute-kbd-macro (kbd "C-/ M-2"))
  (should (looking-back "first"))

  (kill-buffer))

;; Let's enter Python mode and see how things change

(ert-deftest company-shows-keywords-alongside-completions-alphabetically ()
  :tags '(company)
  (skip-unless (fboundp 'company-manual-begin))
  (switch-to-buffer "*TESTING COMPANY MODE ~ Python*")
  (python-mode)

  ;; Ensure we have a clear buffer, and enter some text. (Namely, Python code).
  (erase-buffer)
  (insert "\n def first(x): pass")
  (insert "\n def fierce(a, b): pass")

  ;; There are 3 completion candidates: The two we wrote, & the third being a Python keyword.
  (insert "\n fi")
  (company-manual-begin)
  (should (equal company-candidates '("fierce" "first" #("finally" 0 7 (company-backend company-keywords)))))

  ;; Candidates are shown alphabetically: M-2 yields “finally”.
  (execute-kbd-macro (kbd "C-g C-/ M-2")) ;; Quit and restart the completion, to get to starting position, then M-2.
  (should (looking-back "finally"))

  (kill-buffer))

;; [[file:init.org::*E2E Test][E2E Test:1]]
(require 'lf) ;; For `lf-unindent'; installed via use-package but deferred.

(defun my/test--name-to-username (full-name)
  "Derive a Gerrit-style username from FULL-NAME.
Lowercases the first initial and surname: \"Grace Hopper\" → \"ghopper\"."
  (let ((parts (s-split " " (s-trim full-name))))
    (downcase (concat (substring (car parts) 0 1)
                      (car (last parts))))))

(defun my/as-gerrit-patch (spec)
  "Parse a human-readable SPEC string into a Gerrit change alist.
SPEC is a terse commit-message-like block.  Leading indentation is
stripped via `lf-unindent', so callers can indent the string to
match surrounding code:

  (my/as-gerrit-patch \"
      [core] Fix the frobnicate

      BUG-42 #progress

      Change-Id: 101
      Owner: Grace Hopper
      Reviewer: Alan Turing
      Reviewer: Ada Lovelace\")

The first non-blank line becomes `subject'.  Everything before the
metadata lines (Change-Id, Owner, Reviewer) forms `commitMessage'.
`Change-Id' doubles as the Gerrit change `number' and must be a
numeric string (parsed via `string-to-number').  `Owner' populates the
`owner' alist.  Each `Reviewer' line produces an approval entry in
`currentPatchSet' with type \"Code-Review\"."
  (let* ((lines (s-lines (s-trim (lf-unindent spec))))
         (subject (car lines))
         ;; Partition into commit-message vs. metadata lines.
         (meta-re "^\\(Change-Id\\|Owner\\|Reviewer\\):")
         (msg-lines (-take-while
                     (lambda (l) (not (s-matches-p meta-re l)))
                     lines))
         (meta-lines (-drop (length msg-lines) lines))
         (commit-msg (s-trim (s-join "\n" msg-lines)))
         ;; Parse metadata.
         (number nil) (owner-name nil) (reviewers nil))
    (dolist (l meta-lines)
      (cond
       ((s-prefix-p "Change-Id:" l)
        (setq number (string-to-number (s-trim (substring l 10)))))
       ((s-prefix-p "Owner:" l)
        (setq owner-name (s-trim (substring l 6))))
       ((s-prefix-p "Reviewer:" l)
        (push (s-trim (substring l 9)) reviewers))))
    (setq reviewers (nreverse reviewers))
    `((number . ,number)
      (subject . ,subject)
      (commitMessage . ,commit-msg)
      (owner (name . ,owner-name)
             (username . ,(my/test--name-to-username owner-name)))
      (currentPatchSet
       (approvals . ,(-map (lambda (r)
                             `((type . "Code-Review")
                               (by (name . ,r)
                                   (username
                                    . ,(my/test--name-to-username r)))))
                           reviewers))))))

(defun my/as-gerrit-stack (&rest specs)
  "Map `my/as-gerrit-patch' over SPECS, returning a list of change alists.
Each element of SPECS is a human-readable patch string (see
`my/as-gerrit-patch' for the format).  A single-element list is
a valid stack — useful for the lone-change happy path."
  (-map #'my/as-gerrit-patch specs))

(deftestfixture defworkitemtest
  "Bind Gerrit/Jira config vars that work-item functions read,
so tests run without private.el."
  (let ((my\jira-ticket-regex "\\(BUG-[0-9]+\\)")
        (my\gerrit-base-url "https://gerrit.example.com")
        (my\gerrit-project-path "/c/repo/+/"))
    &body))

(defworkitemtest "work-item-to-string shows the tip's Jira ticket when the stack intersection is empty" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[core] Refactor helper

                  Change-Id: 100
                  Owner: Grace Hopper"

                 "[core] Add frobnicate validation

                  BUG-42 #progress

                  Change-Id: 101
                  Owner: Grace Hopper"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-42" rendered))
    (should (s-contains-p "Grace Hopper" rendered))))

(defworkitemtest "work-item-to-string shows the shared Jira ticket when every change references it" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[lang] Step one

                  BUG-7 #progress

                  Change-Id: 200
                  Owner: Ada Lovelace"

                 "[lang] Step two

                  BUG-7 #progress

                  Change-Id: 201
                  Owner: Ada Lovelace"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-7" rendered))
    (should (s-contains-p "Ada Lovelace" rendered))))

(defworkitemtest "work-item-to-string shows Jira ticket for a single-change stack" [work-item]
  (let* ((stack (my/as-gerrit-stack
                 "[ui] Fix button alignment

                  BUG-101 #progress

                  Change-Id: 300
                  Owner: Alan Turing"))
         (item (work-item-from-stack stack 'reviews-needed))
         (rendered (work-item-to-string item)))
    (should (s-contains-p "BUG-101" rendered))
    (should (s-contains-p "Alan Turing" rendered))))
;; E2E Test:1 ends here

;; [[file:init.org::*Implementation][Implementation:2]]
(ert-deftest hierarchical-archive-merges-duplicate-headings ()
  "Archiving a child, then its parent, produces a single merged heading."
  :tags '(archive)
  ;; `org-archive-finalize-hook' was introduced in Org 9.8; the hook
  ;; that drives hierarchical archiving simply doesn't fire on older Org.
  (skip-unless (version<= "9.8" org-version))
  (let* ((src-file (make-temp-file "archive-src" nil ".org"
                                   "* A\nSome useful context\n** B\nMore Info\n** C\nBye!\n"))
         (archive-file (concat (file-name-sans-extension src-file) "_archive.org"))
         (org-archive-location (concat archive-file "::"))
         ;; Suppress prompts and messages during the test.
         (inhibit-message t))
    (unwind-protect
        (progn
          ;; Archive ** B
          (find-file src-file)
          (goto-char (point-min))
          (search-forward "** B")
          (my/org-archive-subtree-hierarchically)

          ;; Archive * A (which still carries ** C)
          (goto-char (point-min))
          (search-forward "* A")
          (my/org-archive-subtree-hierarchically)

          ;; Verify: the archive should contain a single * A with
          ;; body text, ** B, and ** C --- no duplicates.
          (with-current-buffer (find-file-noselect archive-file)
            (let ((contents (buffer-string)))
              ;; Exactly one "* A" heading.
              (should (= 1 (s-count-matches "^\\* A$" contents)))
              ;; Body text from the parent is present.
              (should (s-contains-p "Some useful context" contents))
              ;; Both children are present.
              (should (s-contains-p "** B" contents))
              (should (s-contains-p "More Info" contents))
              (should (s-contains-p "** C" contents))
              (should (s-contains-p "Bye!" contents)))))

      ;; Cleanup: silence kill-buffer prompts for modified buffers.
      (--each (list src-file archive-file)
        (-when-let (buf (get-file-buffer it))
          (with-current-buffer buf (set-buffer-modified-p nil))
          (kill-buffer buf))
        (when (file-exists-p it) (delete-file it))))))
;; Implementation:2 ends here

(ert-deftest lsp-hover-shows-type-signature ()
  (skip-unless (fboundp 'lsp-workspace-folders-add))
  ;; Make a temporary scratch.js file with the given contents.
  (-let [scratch.js (make-temp-file "scratch" nil ".js" "const first = (x, y) => 3")]
    (find-file scratch.js)
    (lsp-workspace-folders-add (f-parent scratch.js))
    (lsp)

    ;; lsp-hover uses lsp--eldoc-message, so let's save the hover info.
    (advice-add #'lsp--eldoc-message :before (lambda (&rest msg) (setq my/lsp-hover-message (substring-no-properties (car msg)))))

    (end-of-buffer)
    (insert "\n first")
    (lsp-hover)  ;; Alternatively: (lsp-describe-thing-at-point)
    (should (equal "const first: (x: any, y: any) => number" my/lsp-hover-message))

    (save-buffer)
    (kill-buffer)))
