# [[file:../../init.org::#Github-Actions][Github Actions:1]]
# This workflow will do a clean install of dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/

name: Lifemacs Loads Successfully

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Set up Emacs
        uses: purcell/setup-emacs@v8.0
        with:
          version: 30.1

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.

      - name: where am I and what is here
        run: |
          pwd
          ls

      - name: Install Org from GNU ELPA
        run: emacs -nw --batch --eval='(progn
                              (require (quote package))
                              (add-to-list (quote package-archives)
                                           (quote ("gnu" . "https://elpa.gnu.org/packages/")))
                              (package-initialize)
                              (package-refresh-contents)
                              (package-install (quote org))
                              (message "Installed Org %s" (org-version)))'

      - name: Startup smoke test
        run: time emacs -nw --batch --eval='(let
                                (
                                 (user-emacs-directory default-directory))
                              (message "Default directory" )
                              (message default-directory)
                              (setq url-show-status nil)
                              (package-initialize)
                              (load-file "init.el")
                              (message "\n 🤤 Startup Successful! 🤩"))'

      - name: Run ERT tests
        run: time emacs -nw --batch --eval='(let
                                ((user-emacs-directory default-directory))
                              (setq url-show-status nil)
                              (package-initialize)
                              (load-file "init.el")
                              (load-file "init-test.el")
                              (ert-run-tests-batch-and-exit))'
# Github Actions:1 ends here
